sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.1
- 2.4.1
- 2.5.0
- 2.6.0
- ruby-head
gemfile:
- gemfiles/Gemfile.rails4
- gemfiles/Gemfile.rails5_1
- gemfiles/Gemfile.rails5_2
before_install: gem update --system
bundler_args: "--without vscode"
script:
- bundle exec rspec
- bundle exec rspec --tag integration
after_script:
- bundle exec codeclimate-test-reporter
matrix:
  allow_failures:
  - rvm: ruby-head
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8dfbb94cdb25ff174f4e
deploy:
  provider: rubygems
  api_key:
    secure: Ynt1TYffHV1wL2wmGOnLe+D7OXLPpbh4ZYgGjXC6Ru690kQYQwYQVzsvZ7ClZ+fJBQoYmdFNqbBTdkA5nxp0fbRq9ZpMbEunxcoWhXaZLczMoh2kP4YUKowv/Wmq3vzh64irzUZHN/ykYPNeqoZQmqD3QiWIShJCvN6cMXEQlF85s830XUoBNGwCYx1gC1mVI8SQizbsnAS/hmCoXp+fS6igu+GmQuYzyuZZy8+L+RlHQDronFH7C2C2dOpvMPPhrlSsLMTIosJ48Ib+afhBBMO3VuLu0hgrIkwlI9e9YtTELEtNxdNJDtbRSFQuXn8cOLL7Zv6hfWpcxiWk5EoCD9rtT5BQFWjzshoBsZtCRxCke5nId/AB1eztIKF9KrH4uir+aURqp7irKK+eITMJ0obDz/pe/GLgAVU68zJmKSOUvlRernumAy0beiyu/0Zr3YO51+2EDo+uT2x5f7ANgzmUuvLh9grWG+Ld2N1bqESw/cvmilfwzzUtLUSd0hA8aOtvMOcEpS5GAbqY59TeZ+SR2dIuGoIN2qkHTKF5M7HwIKDUM2gFUZM32xHkoX+MrPzuY7hAq9n79QhprAjUqdjIbJVvvXLwZadI5gjFtaBV4p3Ah19JAN6y+NX0mkDI1bSCQoQUDiSRRMz+pZJt2qo+WF3Q9H8tcc14nHV9v8E=
  gem: rakuten_web_service-rails
  on:
    repo: satoryu/rakuten_web_service-rails
    condition: "$TRAVIS_RUBY_VERSION = 2.5.0"
addons:
  code_climate:
    repo_token:
      secure: daHyv4oum5q/gRA/7S3USdf5jlninNNEhweKDeOHfgTLAafEXSq87DOqfbjw3ug0Kxur0JtwPHcooEwMLJDq5kDAwpRTdProdlN9HAkSJ9eHEaN3azgnxOraAEIoyXkqiUqddLpJ+An2rbagemZRykPG78SWwKAkDUBG0iDaZsBPN1KSj5a+NjdFGMy7q1YPcfQHWT753AE4SjiNdFv29WP3mLIJSkDRBqIdMGMzqPxX4I03baSqmO9+6JmQN/zAy/bjmpf74OemDa0PiLxgzDaDvys0sI6ecYPxNlfYdRNDqPN+YIXZzio6yMIrFwGv7T+Lwr3CJ66pMAy9Hj+3BEj2TpBeHZS4d0eR1rDDBJKczL+kd/v8ZInFnovELKI6OdWImYJCcUrBMoY7pEOqIao9MIjgHtOONcKaxXgZOa6HuJUwihNcy4sdmH2qnCz0Cx0UIwrHLXG0iDq90WYkwbLF4WnXK2XmMQyVRqAgEFEE/Gfxsnr1SqQJAkmT7UR5GzdQREI9S9aCseW3IKMrSbkpSIOXlmF+oFHyAU7Z3LZ3Zp9l6te7csDb9PeGuXlG1tQ+BfWg2ddwTxNNOBFFS2OgWGa1ZB7zBprS3khg0oUOJ4nlivFgz0l7d41kvmvBOWeINKtlSf5aI5M1hoKaRV2WbmCTLNkhbCZe0/8N8Q4=
