sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.9
- 2.2.5
- 2.3.1
- 2.4.1
gemfile:
- gemfiles/Gemfile.rail4
- gemfiles/Gemfile.rail5
before_install: gem install bundler -v 1.12.5
script:
- bundle exec rspec
- bundle exec rspec --tag integration
matrix:
  exclude:
  - rvm: 2.1.9
    gemfile: gemfiles/Gemfile.rail5
notifications:
  email: false
  hipchat:
    rooms:
      secure: MkaCXbqKaSrfuhX/KYFpOI23BTU7SLMKa+y68ywGLFMPZfg4vlSF2V7BdXQADwomzOe4MK0p3T1YbIydOoXlbCgYBRFfntUGZft8KxCyeQSbaYSDKYRrdyU1pwWwxRT889Z0U9JCgr16F+/HWzA1U3qyMeIyhIiciU1jCeHLtmaP6CtFTFXSoyfDCVGkED+zriFKcTL2uKt2ZK+9D2w2Uq75iGSLmCIGzfMTIN6h69qIVdQac3SDHn6ZtXer0A82vb1WEWfffOELmHl9U5amNN/8UFR/P9YqdJOZjeuzLnC4iL/QHbvhaOYea/z6JBYW/c8P+aZo/4UAFRUfseKomdcLyqTWnG5UJdDHLfWSU5DOpgp5WJn5VFF/vCHN65koNC8PmVatAWDn6nWc+bHcbZ/Vb9YyEMPzOmpxEjJxmuDzzwbbhOhLJDQliT1JwLevhRHWBPbimVju1rKJIkC4p/e2m8uQAukUkadDDPxl70lCivamoFxPWfPczXCUGum9C95OY0678sGoYHvXHqL1cGE1YVMpvT+LHtw3eAMouk3E0u9g8ullJ4tgMnl2CXJ+0s7hwTkvq6HOyRBCDhwP9+w9+XzkgW9DFtxXaykJN3zI9F2Z97EovmqXPY7mbQRstx9HlQhpHtgmg2gZiO9SoiTFbt7DZDMCinaQEdFMzL8=
deploy:
  provider: rubygems
  api_key:
    secure: Ynt1TYffHV1wL2wmGOnLe+D7OXLPpbh4ZYgGjXC6Ru690kQYQwYQVzsvZ7ClZ+fJBQoYmdFNqbBTdkA5nxp0fbRq9ZpMbEunxcoWhXaZLczMoh2kP4YUKowv/Wmq3vzh64irzUZHN/ykYPNeqoZQmqD3QiWIShJCvN6cMXEQlF85s830XUoBNGwCYx1gC1mVI8SQizbsnAS/hmCoXp+fS6igu+GmQuYzyuZZy8+L+RlHQDronFH7C2C2dOpvMPPhrlSsLMTIosJ48Ib+afhBBMO3VuLu0hgrIkwlI9e9YtTELEtNxdNJDtbRSFQuXn8cOLL7Zv6hfWpcxiWk5EoCD9rtT5BQFWjzshoBsZtCRxCke5nId/AB1eztIKF9KrH4uir+aURqp7irKK+eITMJ0obDz/pe/GLgAVU68zJmKSOUvlRernumAy0beiyu/0Zr3YO51+2EDo+uT2x5f7ANgzmUuvLh9grWG+Ld2N1bqESw/cvmilfwzzUtLUSd0hA8aOtvMOcEpS5GAbqY59TeZ+SR2dIuGoIN2qkHTKF5M7HwIKDUM2gFUZM32xHkoX+MrPzuY7hAq9n79QhprAjUqdjIbJVvvXLwZadI5gjFtaBV4p3Ah19JAN6y+NX0mkDI1bSCQoQUDiSRRMz+pZJt2qo+WF3Q9H8tcc14nHV9v8E=
  gem: rakuten_web_service-rails
  on:
    tags: true
    repo: satoryu/rakuten_web_service-rails