development:
  application_id: development_application_id
  affiliate_id: development_affiliate_id

test:
  application_id: rails_application_id
  affiliate_id: <%= ENV['AFFILIATE_ID'] %>

production:
  application_id: development_application_id
  affiliate_id: development_affiliate_id
